# configs/model_configs/feature_graph.yaml
logging:
  level: INFO
  feature_shapes: true

dataset:
  name: "NIH-ChestXray14"
  image_size: 224
  num_classes: 14
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

  positive_counts: [ 7996, 1950, 9261, 13914, 3988, 4375, 978, 3705, 3263, 1690, 1799, 1158, 2279, 144 ]
  negative_counts: [ 70472, 76518, 69207, 64554, 74480, 74093, 77490, 74763, 75205, 76778, 76669, 77310, 76189, 78324 ]

  train_csv: "/users/gm00051/ChestX-ray14/labels/train_list.txt"
  val_csv: "/users/gm00051/ChestX-ray14/labels/val_list.txt"
  test_csv: "/users/gm00051/ChestX-ray14/labels/test_list.txt"
  image_dir: "/users/gm00051/ChestX-ray14/images"
  bb_annotations: "/users/gm00051/ChestX-ray14/labels/BBox_List_2017.csv"

  classes: [
    'Atelectasis', 'Cardiomegaly', 'Effusion', 'Infiltration', 'Mass',
    'Nodule', 'Pneumonia', 'Pneumothorax', 'Consolidation', 'Edema',
    'Emphysema', 'Fibrosis', 'Pleural_Thickening', 'Hernia'
  ]


model:
  name: "feature_graph"
  baseline_checkpoint: "/users/gm00051/projects/cvpr/baseline/Graph-Augmented-Vision-Transformers/scripts/checkpoints/checkpoint_epoch_82_auc_0.7225.pt"
  feature_dim: 768
  graph_hidden_dim: 256
  num_graph_layers: 2
  dropout_rate: 0.1
  fusion_type: "concat_mlp"
  freeze_backbone: true


training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 1e-4
  weight_decay: 1e-4
  warmup_epochs: 5
  checkpoint_dir: "outputs/feature_graph/checkpoints"
  num_workers: 4
  loss_weights:
    wbce: 1.0
    focal: 1.0
    asl: 1.0
  patience: 10
  log_interval: 100
  use_amp: true
  gradient_clip_val: 1.0



wandb:
  project: "chest-xray-classification"
  entity: "mirzaeeghazal"
  tags: ["feature-graph", "development"]

gpu:
  device: 0  # GPU device index to use
  strategy: "ddp"  # DDP for multi-GPU training
  sync_batchnorm: true

