# configs/data_configs/nih_chestxray.yaml
dataset:
  name: "NIH-ChestXray14"
  image_size: 224
  num_classes: 14
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

paths:
  train_csv: "/users/gm00051/ChestX-ray14/labels/train_list.txt"
  val_csv: "/users/gm00051/ChestX-ray14/labels/val_list.txt"
  test_csv: "/users/gm00051/ChestX-ray14/labels/test_list.txt"
  image_dir: "/users/gm00051/ChestX-ray14/images"
  bb_annotations: "/users/gm00051/ChestX-ray14/labels/BBox_List_2017.csv"

