
# configs/gpu_configs/a30.yaml
device:
  name: "A30"
  memory: 24  # GB
  compute_capability: "8.0"
  optimization:
    mixed_precision: true
    channels_last: true
    cudnn_benchmark: true
    memory_pinning: true
    optimal_batch_size: auto
    gradient_accumulation: 2

training:
  precision: 16
  accelerator: "gpu"
  strategy: "ddp"
  sync_batchnorm: true
  default_root_dir: "checkpoints"
  max_epochs: 100
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
  deterministic: false


