# Dataset paths
data_root: "/users/gm00051/ChestX-ray14/categorized_images"
train_split: "train"
val_split: "val"
test_split: "test"

# Image size
image_size: 224

# Class names
diseases:
  - "Atelectasis"
  - "Cardiomegaly"
  - "Effusion"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pneumonia"
  - "Pneumothorax"
  - "Consolidation"
  - "Edema"
  - "Emphysema"
  - "Fibrosis"
  - "Pleural_Thickening"
  - "Hernia"

# Class weights for handling imbalance
class_weights:
  Atelectasis: 1.90
  Cardiomegaly: 8.46
  Effusion: 1.61
  Infiltration: 1.00
  Mass: 4.03
  Nodule: 3.65
  Pneumonia: 17.08
  Pneumothorax: 4.35
  Consolidation: 4.97
  Edema: 9.79
  Emphysema: 9.19
  Fibrosis: 14.39
  Pleural_Thickening: 7.21
  Hernia: 117.24

