# Dataset paths
train_paths: "/users/gm00051/ChestX-ray14/categorized_images/train"
val_paths: "/users/gm00051/ChestX-ray14/categorized_images/val"
test_paths: "/users/gm00051/ChestX-ray14/categorized_images/test"
train_labels: "/users/gm00051/ChestX-ray14/labels/train_list.txt"
val_labels: "/users/gm00051/ChestX-ray14/labels/val_list.txt"
test_labels: "/users/gm00051/ChestX-ray14/labels/test_list.txt"
bbox_data_path: "/users/gm00051/ChestX-ray14/labels/BBox_List_2017.csv"


# Model configuration
model:
  pretrained_path: "/users/gm00051/projects/cvpr/baseline/Graph-Augmented-Vision-Transformers/scripts/checkpoints/checkpoint_epoch_82_auc_0.7225.pt"
  feature_dim: 768
  hidden_dim: 512
  num_diseases: 14
  graph_layers: 2
  dropout: 0.1

# Training configuration
training:
  batch_size: 32
  num_epochs: 1
  learning_rate: 0.0001
  weight_decay: 0.01
  patience: 10  # Early stopping patience
  num_workers: 4
  checkpoint_dir: "/users/gm00051/projects/cvpr/baseline-feature/results/checkpoints"

# Loss weights
loss_weights:
  wbce: 1.0
  focal: 1.0
  asymmetric: 1.0

# Checkpointing
checkpoint_dir: "checkpoints"
save_frequency: 5

# Logging
wandb:
  project: "Graph-Augmented ViT"
  entity: "mirzaeeghazal"
  run_name: "baseline+feature"
