# Dataset paths
train_paths: "/path/to/train/images"
val_paths: "/path/to/val/images"
test_paths: "/path/to/test/images"
bbox_data_path: "/path/to/bbox/annotations.csv"

# Model configuration
model:
  num_diseases: 14
  feature_dim: 768
  hidden_dim: 512
  pretrained_path: "/path/to/pretrained/weights.pt"

# Training configuration
training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.01
  patience: 10  # For early stopping
  num_workers: 4

# Loss weights
loss_weights:
  wbce: 1.0
  focal: 1.0
  asymmetric: 1.0

# Checkpointing
checkpoint_dir: "checkpoints"
save_frequency: 5

# Logging
wandb:
  project: "chest-xray-classification"
  entity: "your-username"
  run_name: "graph-augmented-vit"

